### ISSUE TITLE
Blob is not defined

### ISSUE THREAD

**Issue by rafaelvicio** [readyplayerme/visage#27]
I'm having trouble building a web application on AWS Amplify

`2023-05-23T02:19:17.354Z [WARNING]: Error occurred prerendering page "/account/settings/avatar". Read more: https://nextjs.org/docs/messages/prerender-error
                                    ReferenceError: Blob is not defined
                                    at validateGlbSource (/codebuild/output/src051525772/src/rift/node_modules/@readyplayerme/visage/dist/index.cjs.js:88:27)
                                    at isValidGlbFormat (/codebuild/output/src051525772/src/rift/node_modules/@readyplayerme/visage/dist/index.cjs.js:94:21)
                                    at /codebuild/output/src051525772/src/rift/node_modules/@readyplayerme/visage/dist/index.cjs.js:664:13
                                    at Object.Kc [as useMemo] (/codebuild/output/src051525772/src/rift/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
                                    at Object.exports.useMemo (/codebuild/output/src051525772/src/rift/node_modules/react/cjs/react.production.min.js:25:208)
                                    at Avatar (/codebuild/output/src051525772/src/rift/node_modules/@readyplayerme/visage/dist/index.cjs.js:654:31)
                                    at Wc (/codebuild/output/src051525772/src/rift/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
                                    at Zc (/codebuild/output/src051525772/src/rift/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
                                    at Z (/codebuild/output/src051525772/src/rift/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
                                    at $c (/codebuild/output/src051525772/src/rift/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
2023-05-23T02:19:17.493Z [INFO]: info  - Generating static pages (34/136)
2023-05-23T02:19:17.784Z [WARNING]: Error occurred prerendering page "/en/account/settings/avatar". Read more: https://nextjs.org/docs/messages/prerender-error
                                    ReferenceError: Blob is not defined
                                    at validateGlbSource (/codebuild/output/src051525772/src/rift/node_modules/@readyplayerme/visage/dist/index.cjs.js:88:27)
                                    at isValidGlbFormat (/codebuild/output/src051525772/src/rift/node_modules/@readyplayerme/visage/dist/index.cjs.js:94:21)
                                    at /codebuild/output/src051525772/src/rift/node_modules/@readyplayerme/visage/dist/index.cjs.js:664:13
                                    at Object.Kc [as useMemo] (/codebuild/output/src051525772/src/rift/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
                                    at Object.exports.useMemo (/codebuild/output/src051525772/src/rift/node_modules/react/cjs/react.production.min.js:25:208)
                                    at Avatar (/codebuild/output/src051525772/src/rift/node_modules/@readyplayerme/visage/dist/index.cjs.js:654:31)
                                    at Wc (/codebuild/output/src051525772/src/rift/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
                                    at Zc (/codebuild/output/src051525772/src/rift/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
                                    at Z (/codebuild/output/src051525772/src/rift/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
                                    at $c (/codebuild/output/src051525772/src/rift/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
2023-05-23T02:19:17.787Z [WARNING]: Error occurred prerendering page "/pt/account/settings/avatar". Read more: https://nextjs.org/docs/messages/prerender-error
                                    ReferenceError: Blob is not defined
                                    at validateGlbSource (/codebuild/output/src051525772/src/rift/node_modules/@readyplayerme/visage/dist/index.cjs.js:88:27)
                                    at isValidGlbFormat (/codebuild/output/src051525772/src/rift/node_modules/@readyplayerme/visage/dist/index.cjs.js:94:21)
                                    at /codebuild/output/src051525772/src/rift/node_modules/@readyplayerme/visage/dist/index.cjs.js:664:13
                                    at Object.Kc [as useMemo] (/codebuild/output/src051525772/src/rift/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
                                    at Object.exports.useMemo (/codebuild/output/src051525772/src/rift/node_modules/react/cjs/react.production.min.js:25:208)
                                    at Avatar (/codebuild/output/src051525772/src/rift/node_modules/@readyplayerme/visage/dist/index.cjs.js:654:31)
                                    at Wc (/codebuild/output/src051525772/src/rift/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
                                    at Zc (/codebuild/output/src051525772/src/rift/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
                                    at Z (/codebuild/output/src051525772/src/rift/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
                                    at $c (/codebuild/output/src051525772/src/rift/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
2023-05-23T02:19:18.080Z [INFO]: info  - Generating static pages (68/136)
2023-05-23T02:19:18.476Z [WARNING]: Error occurred prerendering page "/default/account/settings/avatar". Read more: https://nextjs.org/docs/messages/prerender-error
                                    ReferenceError: Blob is not defined
                                    at validateGlbSource (/codebuild/output/src051525772/src/rift/node_modules/@readyplayerme/visage/dist/index.cjs.js:88:27)
                                    at isValidGlbFormat (/codebuild/output/src051525772/src/rift/node_modules/@readyplayerme/visage/dist/index.cjs.js:94:21)
                                    at /codebuild/output/src051525772/src/rift/node_modules/@readyplayerme/visage/dist/index.cjs.js:664:13
                                    at Object.Kc [as useMemo] (/codebuild/output/src051525772/src/rift/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:60:240)
                                    at Object.exports.useMemo (/codebuild/output/src051525772/src/rift/node_modules/react/cjs/react.production.min.js:25:208)
                                    at Avatar (/codebuild/output/src051525772/src/rift/node_modules/@readyplayerme/visage/dist/index.cjs.js:654:31)
                                    at Wc (/codebuild/output/src051525772/src/rift/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
                                    at Zc (/codebuild/output/src051525772/src/rift/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
                                    at Z (/codebuild/output/src051525772/src/rift/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
                                    at $c (/codebuild/output/src051525772/src/rift/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
2023-05-23T02:19:19.069Z [WARNING]: Warning: data for page "/calendar/past" (path "/calendar/past/") is 242 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
                                    See more info here: https://nextjs.org/docs/messages/large-page-data
2023-05-23T02:19:19.083Z [WARNING]: Warning: data for page "/calendar/past" (path "/calendar/past/") is 242 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
                                    See more info here: https://nextjs.org/docs/messages/large-page-data
2023-05-23T02:19:19.117Z [WARNING]: Warning: data for page "/calendar/past" (path "/calendar/past/") is 242 kB which exceeds the threshold of 128 kB, this amount of data can reduce performance.
                                    See more info here: https://nextjs.org/docs/messages/large-page-data
2023-05-23T02:19:19.117Z [INFO]: info  - Generating static pages (102/136)
2023-05-23T02:19:20.592Z [INFO]: info  - Generating static pages (136/136)
2023-05-23T02:19:20.594Z [WARNING]: 
2023-05-23T02:19:20.595Z [WARNING]: > Build error occurred
2023-05-23T02:19:20.597Z [WARNING]: Error: Export encountered errors on following paths:
                                    /account/settings/avatar
                                    /account/settings/avatar: /default/account/settings/avatar
                                    /account/settings/avatar: /en/account/settings/avatar
                                    /account/settings/avatar: /pt/account/settings/avatar
                                    at /codebuild/output/src051525772/src/rift/node_modules/next/dist/export/index.js:415:19
                                    at processTicksAndRejections (node:internal/process/task_queues:96:5)
                                    at async Span.traceAsyncFn (/codebuild/output/src051525772/src/rift/node_modules/next/dist/trace/trace.js:79:20)
                                    at async /codebuild/output/src051525772/src/rift/node_modules/next/dist/build/index.js:1400:21
                                    at async Span.traceAsyncFn (/codebuild/output/src051525772/src/rift/node_modules/next/dist/trace/trace.js:79:20)
                                    at async /codebuild/output/src051525772/src/rift/node_modules/next/dist/build/index.js:1259:17
                                    at async Span.traceAsyncFn (/codebuild/output/src051525772/src/rift/node_modules/next/dist/trace/trace.js:79:20)
                                    at async Object.build [as default] (/codebuild/output/src051525772/src/rift/node_modules/next/dist/build/index.js:66:29)
2023-05-23T02:19:20.748Z [WARNING]: error Command failed with exit code 1.
`

`    "@react-three/drei": "^9.65.3",
    "@react-three/fiber": "^8.12.0",
    "@readyplayerme/visage": "^3.5.2",`

Node.js version
17

**Comment by Zaehiel** [comment]
Hi!
Could you provide a reproduction sandbox? It's not clear if it's an issue with Visage or your development environment.

**Comment by Zaehiel** [comment]
Closed due to not enough information
